AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: ntier node server AWS Lambda function.

Resources:

  Serverless02:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Description: ntier node server AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "Cities"

Outputs:
  MyFunctionName:
    Description: My Function Name
    Value:
      Fn::GetAtt: ServerLess02.Arn
    Export:
      Name: NodeServerLambdaName
